# Generated by Django 6.0.4 on 2026-05-05 12:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddService',
            fields=[
                ('add_service_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('content', models.TextField()),
                ('cost', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('hotel_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('address', models.TextField()),
                ('rating', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Tour_operator',
            fields=[
                ('tour_operator_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('address', models.TextField()),
                ('site', models.TextField()),
                ('email', models.TextField()),
                ('country', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('transport_id', models.AutoField(primary_key=True, serialize=False)),
                ('carrier', models.TextField()),
                ('type', models.TextField()),
                ('way', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('program_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('services', models.TextField()),
                ('description', models.TextField()),
                ('country', models.TextField()),
                ('city', models.TextField()),
                ('meal', models.TextField()),
                ('duration', models.IntegerField(default=0)),
                ('persons', models.TextField()),
                ('activities', models.TextField()),
                ('hotel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turag.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('tour_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('date_start', models.DateTimeField(auto_now_add=True)),
                ('date_end', models.DateTimeField(auto_now_add=True)),
                ('cost_for_one_person', models.IntegerField(default=0)),
                ('hotel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turag.hotel')),
                ('program_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turag.program')),
                ('tour_operator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turag.tour_operator')),
                ('transport_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turag.transport')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('add_service_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turag.addservice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tour_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turag.tour')),
            ],
        ),
        migrations.CreateModel(
            name='comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('rate', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tour_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turag.tour')),
            ],
        ),
    ]
