# Generated by Django 6.0.4 on 2026-05-06 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turag', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='addservice',
            old_name='title',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='user',
            new_name='user_id',
        ),
        migrations.RenameField(
            model_name='program',
            old_name='country',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='program',
            name='title',
        ),
        migrations.AddField(
            model_name='tour',
            name='comments',
            field=models.ManyToManyField(to='turag.comment'),
        ),
        migrations.AddField(
            model_name='tour',
            name='country',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='transport',
            name='name',
            field=models.TextField(default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='addservice',
            name='cost',
            field=models.IntegerField(),
        ),
    ]
