# Generated by Django 6.0.4 on 2026-05-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turag', '0002_rename_title_addservice_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='duration',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
