# Generated by Django 6.0.4 on 2026-05-06 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turag', '0003_tour_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='program',
            name='persons',
        ),
        migrations.AddField(
            model_name='tour',
            name='persons',
            field=models.TextField(default=''),
        ),
    ]
