# Generated by Django 6.0.4 on 2026-05-06 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turag', '0004_remove_program_duration_remove_program_persons_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tour_operator',
            new_name='TourOperator',
        ),
        migrations.AddField(
            model_name='hotel',
            name='country',
            field=models.TextField(default=''),
        ),
    ]
