# Generated by Django 6.0.4 on 2026-05-06 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turag', '0005_rename_tour_operator_touroperator_hotel_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='touroperator',
            name='country',
            field=models.TextField(default=''),
        ),
    ]
