# Generated by Django 6.0.4 on 2026-05-06 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turag', '0006_alter_touroperator_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='comments',
            field=models.ManyToManyField(default='', to='turag.comment'),
        ),
    ]
