# Generated by Django 6.0.4 on 2026-05-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turag', '0007_alter_tour_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tour',
            name='persons',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
